spring:
  datasource:
    username: root
    password: lu1991101
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.lucas.pojo
  mapper-locations: classpath:mapper/*.xml
